### ISSUE TITLE
Support empty Vespa cluster

### ISSUE THREAD

**Issue by pehrs** [vispana/vispana#25]
Vispana will just fail and give an error, if you start up an "empty" cluster (a cluster with no application deployed)
Vispana should at least show the config nodes and their state.

The use case:
When creating a new cluster it would be nice to use Vispana to see if the cluster is in a healthy state to deploy the application.

**Comment by broknloop** [comment]
I took a stab at this, but it seems like there is a limitation on Vespa API that doesn't allow us to query metrics or most of the APIs when no application has been deployed.

**Comment by broknloop** [comment]
Merged [this PR](https://github.com/vispana/vispana/commit/56ecb821938b78bfb83cf14748afaf0e400870b9) that hopefully will help guiding users to the problem at hand
